In [1]:
import numpy as np

In [2]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([0,1,1,0])


In [3]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [34]:
X.shape

(4, 2)

In [4]:
Y

array([0, 1, 1, 0])

In [5]:
bias = np.ones(len(X), dtype=np.int32)
bias.reshape(-1,1)

array([[1],
       [1],
       [1],
       [1]])

In [8]:
bias

array([1, 1, 1, 1])

In [10]:
input_X = np.hstack([X,bias.reshape(-1,1)])
input_X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [12]:
hidden_node = 2
W1 = np.random.rand(len(input_X[0]),hidden_node)

In [13]:
def sigmoid(a):
    return 1 / (1+np.exp(-a))

In [14]:
H = sigmoid(input_X.dot(W1))
H

array([[0.54609955, 0.70115812],
       [0.75631454, 0.77725145],
       [0.62426753, 0.7680984 ],
       [0.81082156, 0.83124916]])

In [15]:
input_H = np.hstack([H, np.ones(len(X)).reshape(-1, 1)])
input_H

array([[0.54609955, 0.70115812, 1.        ],
       [0.75631454, 0.77725145, 1.        ],
       [0.62426753, 0.7680984 , 1.        ],
       [0.81082156, 0.83124916, 1.        ]])

In [16]:
W2 = np.random.rand(hidden_node+1, 1)
W2

array([[0.55619595],
       [0.46990931],
       [0.24481652]])

In [18]:
y_hat = sigmoid(input_H.dot(W2))

In [19]:
y_hat

array([[0.70641499],
       [0.73705416],
       [0.72171171],
       [0.74770395]])

In [30]:
loss = y_hat.T - Y

In [31]:
abs_loss = np.abs(diff)

In [32]:
abs_loss

array([[0.70641499, 0.26294584, 0.27828829, 0.74770395]])

In [39]:
# gradient 계산
dL_dy = y_hat - Y.reshape(-1,1)  # 손실함수를 예측값으로 미분한값
dy_da = y_hat * (1-y_hat) # 출력층 환성화함수 시그모이드를 입력값에 대해 미분한값
delta2 = dL_dy * dy_da # 출력층에서 계산된 gradient

grad_W2 = np.dot(input_H.T, delta2)

# hiddnen node gradent 계산
delta2_times_W2 = np.dot(delta2, W2[:-1].T)
dh_dz = H = (1 - H)     #hidden 활성화함수 시그모이드를 z에 대해 미분한 값
delta1 = delta2_times_W2 * dh_dz    # hidden node gradent

grad_W1 = np.dot(input_X.T, delta1)

