In [1]:
## 행렬 연산을 위한 numpy 임포트
import numpy as np

In [2]:
# 데이터 정의
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 0])

In [13]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [6]:
y.shape

(4,)

In [11]:
# input에 bias를 추가하기 위해 데이터 개수만큼 1로 만들어진 배열을 추가
b1 = np.ones(len(X), dtype=np.int32)
b1.reshape(-1, 1)
input_X = np.hstack([X, b1.reshape(-1, 1)])
input_X

In [21]:
# 은닉층(Hidden Layer)의 노드 수 = 2
hidden_node = 2

# 입력층-은닉층에 사용되는 랜덤으로 가중치 행렬인 W1 생성
W1 = np.random.rand(len(input_X[0]), hidden_node)

In [25]:
# sigmoid 함수 정의
def sigmoid(a):
    return 1 / (1+np.exp(-a))

In [26]:
# 행렬곱한 결과에 sigmoid를 씌워서 은닉층 값을 출력
H = sigmoid(input_X.dot(W1))
H

In [32]:
# bias 추가하여 출력층(Output Layer) 계산에 사용하는 입력행렬 생성
input_H = np.hstack([H, np.ones(len(X)).reshape(-1, 1)])
input_H

array([[0.59698215, 0.52438971, 1.        ],
       [0.70131003, 0.69734718, 1.        ],
       [0.72151997, 0.55944964, 1.        ],
       [0.80418378, 0.72631172, 1.        ]])

In [35]:
# 은닉층-출력층을 위한 가중치 행렬
W2 = np.random.rand(hidden_node+1, 1)
W2

array([[0.39070542],
       [0.62676865],
       [0.55569172]])

In [34]:
# sigmoid를 씌워서 최종 output 계산
sigmoid(input_H.dot(W2))

array([[0.79216794],
       [0.82422198],
       [0.8147292 ],
       [0.8406858 ]])

array([0, 1, 1, 0])